### ISSUE TITLE
'cgi' has no attribute 'parse_qs'

### ISSUE THREAD

**Issue by seb128** [powersj/ubuntu-bug-triage#14] opened 2020-08-13 13:10 UTC
Using the snap r200 on a focal xubuntu system, ubuntu-bug-triage prompts in the browser for auth and then fails with that error

```
$ ubuntu-bug-triage 
The authorization page:
 (https://launchpad.net/+authorize-token?oauth_token=DVX9p6cSgkNLzzqxRVj7&allow_permission=DESKTOP_INTEGRATION)
should be opening in your browser. Use your browser to authorize
this program to access Launchpad on your behalf.
Waiting to hear from Launchpad about your decision...
Traceback (most recent call last):
  File "/snap/ubuntu-bug-triage/200/bin/ubuntu-bug-triage", line 8, in <module>
    sys.exit(launch())
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/ubuntu_bug_triage/__main__.py", line 111, in launch
    triage = TeamTriage(
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/ubuntu_bug_triage/triage.py", line 78, in __init__
    self.team = self.launchpad.people[team]
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/lazr/restfulclient/resource.py", line 998, in __getitem__
    shim_resource._ensure_representation()
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/lazr/restfulclient/resource.py", line 379, in _ensure_representation
    representation = self._root._browser.get(self._wadl_resource)
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/lazr/restfulclient/_browser.py", line 448, in get
    response, content = self._request(url, extra_headers=headers)
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/lazr/restfulclient/_browser.py", line 398, in _request
    response, content = self._request_and_retry(
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/lazr/restfulclient/_browser.py", line 368, in _request_and_retry
    response, content = self._connection.request(
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/httplib2/__init__.py", line 1943, in request
    (response, new_content) = self._request(
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/launchpadlib/launchpad.py", line 137, in _request
    return self.retry_on_bad_token(response, content, *args)
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/launchpadlib/launchpad.py", line 148, in retry_on_bad_token
    self.authorization_engine(
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/launchpadlib/credentials.py", line 546, in __call__
    self.make_end_user_authorize_token(credentials, request_token_string)
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/launchpadlib/credentials.py", line 660, in make_end_user_authorize_token
    credentials.exchange_request_token_for_access_token(
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/launchpadlib/credentials.py", line 232, in exchange_request_token_for_access_token
    self.access_token = AccessToken.from_string(content)
  File "/snap/ubuntu-bug-triage/200/lib/python3.8/site-packages/launchpadlib/credentials.py", line 251, in from_string
    params = cgi.parse_qs(query_string, keep_blank_values=False)
AttributeError: module 'cgi' has no attribute 'parse_qs'

```

**Comment by powersj** [comment] 2020-08-13 22:50
I was able to reproduce this in a VM and have discovered that a newer version of launchpadlib (`1.10.6` -> `1.10.13`) has a fix for this. Looks like this was [LP: 1861873](https://bugs.launchpad.net/ubuntu/+source/apport/+bug/1861873). I will update the dependency and update the snap shortly! Thanks!

**Closed as completed** 2020-08-13 22:53 UTC

**Comment by powersj** [comment] 2020-08-13 23:03
Fixed in snap rev 205

**Comment by seb128** [comment] 2020-08-14 09:43
Indeed, the new snap work as expected, thanks!
